name: kd
description: kd applies shell commands to multiple dart and flutter packages at once.
version: 2.1.1
publish_to: none
repository: https://github.com/ggsuite/kd.git

environment:
  sdk: ">=3.8.1<4.0.0"

dependencies:
  args: ^2.4.2
  gg: ^6.1.0
  gg_args: ^2.0.2
  gg_console_colors: ^2.0.2
  gg_local_package_dependencies: ^1.0.0
  gg_log: ^1.0.0
  gg_process: ^1.0.0
  gg_project_root: ^1.0.0
  gg_status_printer: ^1.1.3
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  yaml_edit: ^2.1.1
  kidney_core:
    path: ../kidney_core # ^2.2.2
dev_dependencies:
  fake_async: ^1.3.1
  gg_capture_print: ^1.0.2
  lints: ^6.0.0
  test: ^1.24.0

executables:
  kd: