name: gg_kidney
description: gg_kidney performs maintenance tasks on our various repositories.
version: 1.0.3
repository: https://github.com/inlavigo/gg_kidney.git

environment:
  sdk: ">=3.3.0<4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^1.1.8
  gg_capture_print: ^1.0.2
  gg_console_colors: ^2.0.2
  gg_log: ^1.0.0
  gg_process: ^1.0.0
  gg_project_root: ^1.0.0
  path: ^1.8.0
  pub_semver: ^2.1.4
  yaml_edit: ^2.1.1

dev_dependencies:
  fake_async: ^1.3.1
  gg_install_gg: ^1.0.2
  lints: ^3.0.0
  mocktail: ^1.0.3
  pana: ^0.22.1
  test: ^1.24.0

executables:
  gg_kidney:
